version: '3.8'
services:
  demo:
    build: .
  cli:
    build: 
      dockerfile: ./Dockerfile_cli
  prometheus:
     image: prom/prometheus:latest
     container_name: stanza-api-prometheus
     restart: unless-stopped
     user: root
     volumes:
       - ./prometheus-config:/prometheus-config/
       - prometheus-data:/prometheus/
     command: --web.enable-remote-write-receiver --web.enable-lifecycle  --config.file=/prometheus-config/prometheus.yaml
  grafana:
    build: ./grafana
    ports:
      - '3000:3000'

volumes:
  prometheus-data:
