# Build Stage
FROM golang:1.20-bullseye AS build

LABEL app="stanza-api-cli"
LABEL REPO="https://github.com/StanzaSystems/stanza-api-demo"

WORKDIR /go/src/app
COPY . .
RUN go mod download
RUN go build -o /go/src/app/bin/stanza-api-cli ./cmd/cli

# Final Stage
FROM busybox:1.35.0-uclibc as busybox
FROM gcr.io/distroless/base-debian11

WORKDIR /
COPY --from=build /go/src/app/bin/stanza-api-cli /stanza-api-cli

COPY --from=busybox /bin/sh /bin/sh
COPY --from=busybox /bin/tail /bin/tail

CMD ["tail", "-f", "/dev/null"]