{
 "title": "Stanza API Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Quota Granted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(stanza_demo_quota_granted_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota Not Granted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(stanza_demo_quota_not_granted_total[10s])"
    }
   ]
  },
  {
   "title": "Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(stanza_demo_quota_latency_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(stanza_demo_quota_latency_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stanza Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(stanza_demo_quota_error_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}